trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - master
      - release/*
      - feature/*
      - hotfix/*
  paths:
    exclude:
      - README.md
      - helm-charts/*

stages:
- stage: Independent Build using Docker
  jobs:
  - job: BuildTestPublish
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      DOCKER_CONTAINER_REGISTRY: 'Digital Management System Docker Hub'
      DOCKER_REPOSITORY_NAME: 'digitalmanagementsystem/frontend'

    steps:
    - task: GitVersion@5
      inputs:
        runtime: 'core'
        configFilePath: './GitVersion.yml'

    - task: Docker@2
      displayName: "Build docker image"
      inputs:
        repository: $(DOCKER_REPOSITORY_NAME)
        command: 'build'
        Dockerfile: '$(system.defaultWorkingDirectory)/docker/Dockerfile.build'
        buildContext: '$(system.defaultWorkingDirectory)'
        arguments: '--build-arg VERSION=$(GitVersion.SemVer)'
        tags: $(GitVersion.SemVer)

    - task: Docker@2
      displayName: "Test and Coverage"
      inputs:
        command: 'build'
        Dockerfile: '$(system.defaultWorkingDirectory)/docker/Dockerfile.testAndCoverage'
        buildContext: '$(system.defaultWorkingDirectory)'
        arguments: '--build-arg COVERALLS_SERVICE_NAME=$(COVERALLS_SERVICE_NAME) --build-arg COVERALLS_REPO_TOKEN=$(COVERALLS_REPO_TOKEN)'

    - task: Docker@2
      displayName: "Docker Login"
      inputs:
        containerRegistry: $(DOCKER_CONTAINER_REGISTRY)
        command: 'login'

    - task: Docker@2
      displayName: "Push docker image"
      inputs:
        containerRegistry: $(DOCKER_CONTAINER_REGISTRY)
        repository: $(DOCKER_REPOSITORY_NAME)
        command: 'push'
        buildContext: '$(system.defaultWorkingDirectory)'
        tags: $(GitVersion.SemVer)
       
    - task: Docker@2
      displayName: "Docker Logout"
      inputs:
        containerRegistry: $(DOCKER_CONTAINER_REGISTRY)
        command: 'logout'

- stage: Build made for use in Azure DevOps Release Pipeline
  jobs:
  - job: BuildTestPublish
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: GitVersion@5
      inputs:
        runtime: 'core'
        configFilePath: './GitVersion.yml'
